version: "3.9"
services:
  app:
    build: app/
    platform: linux/arm/v7
    ports:
      - "8080:8080"
  service:
    build: service/
    platform: linux/arm/v7
    privileged: true
    ports:
      - "3000:3000" 

