version: "3.9"
services:
  app:
    image: ribsstaid/radio-app
    ports:
      - "8080:8080"
  service:
    image: ribsstaid/radio-service
    ports:
      - "3000:3000" 
    extra_hosts:
      - "host.docker.internal:host-gateway"

